spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/music_app}
    username: ${DATABASE_USERNAME:music_app}
    password: ${DATABASE_PASSWORD:music_app}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: ${PORT:8080}
